api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from api import views

app_name = 'api'

router = routers.SimpleRouter()
router.register(r'transaction', views.TransactionViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    # url(r'transaction/chart/monthly$',
    #     views.TransactionChartMonthlyDataView.as_view(),
    #     name='api-transaction-chart-data-monthly'
    #     ),
    url(r'account/$',
        views.AccountListView.as_view(),
        name='api-account-list'
        ),

    url(r'currency/$',
        views.CurrencyListView.as_view(),
        name='api-currency-list'
        ),

    url(r'tag/$',
        views.TagListView.as_view(),
        name='api-tag-list')
]

walletweb/models.py
import hashlib

import math
from collections import defaultdict
from decimal import Decimal

from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser, BaseUserManager
from django.contrib.postgres import fields as postgresfields
from django.core import mail
from django.db import models
from django.db.models import F
from django.db.models import Sum
from django.conf import settings
from django.utils.text import slugify

from taggit.managers import TaggableManager
from taggit.models import Tag as TaggitTag


class MTUserManager(BaseUserManager):
    def create_user(self, email, password=None, first_name='', last_name=''):
        user = self.model()

        if not email:
            raise ValueError('An email address must be specified')

        user.email = email

        if password:
            user.set_password(password)
        else:
            user.set_unusable_password()

        user.first_name = first_name or 'MT User'
        user.last_name = last_name or ''

        user.save()

        return user

    def create_superuser(self, email, password, first_name, last_name):
        user = self.create_user(email, password, first_name, last_name)
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True

        user.save()

        return user


class WalletyUser(AbstractBaseUser,
                  PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=50,
                                  blank=True)
    last_name = models.CharField(max_length=50,
                                 blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']
    objects = MTUserManager()

    def get_short_name(self):
        return self.email

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        mail.send_mail(subject, message, from_email, [self.email], **kwargs)

    class Meta:
        db_table = 'walletweb_walletyuser'

    def __str__(self):
        return self.email


class MTModel(models.Model):
    created_at = models.DateTimeField(verbose_name='Created at',
                                      auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Updated at',
                                      auto_now=True)

    class Meta:
        abstract = True


class UserProfile(MTModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    display_currency = models.ForeignKey('Currency', on_delete=models.CASCADE)

    class Meta:
        db_table = 'walletweb_userprofile'

    def __str__(self):
        return 'Profile for {0}'.format(self.user)


class Currency(MTModel):
    sign = models.CharField(verbose_name='Currency Sign',
                            max_length=5)
    name = models.CharField(verbose_name='Currency Name',
                            max_length=100)
    rate = models.FloatField(verbose_name='Rate to USD',
                             default=1.0)

    class Meta:
        db_table = 'walletweb_currency'

    def __str__(self):
        return self.name


class Account(MTModel):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True,
                             on_delete=models.SET_NULL)
    currency = models.ForeignKey(Currency,
                                 verbose_name='Default Account Currency',
                                 null=True,
                                 on_delete=models.SET_NULL)

    @property
    def balance(self):
        # fetch display currency set by user
        display_currency = self.user.userprofile.display_currency

        account_transactions = Transaction.objects.filter(account=self.id)
        # calculate account balance using the display currency rate
        trans_sum = account_transactions.aggregate(trans_sum=Sum(F('amount') * display_currency.rate))[
                        'trans_sum'] or 0

        return trans_sum

    def __str__(self):
        return 'Account %s' % self.name

    class Meta:
        unique_together = ('name', 'user')
        db_table = 'walletweb_account'


class TransactionManager(models.Manager):
    def made_spent_breakdown_for_daterange(self, user, from_date, to_date):
        """
        Returns the total made and total spent for specified user and date range.
        :param user: For specified user
        :param from_date: Start from date
        :param to_date: Ending at date
        :return: tuple (made, spent)
        """
        # for transactions during a certain date range
        transactions_forrange = Transaction.objects.filter(user=user,
                                                            date__gte=from_date,
                                                            date__lte=to_date)

        # breakdown transactions for date range by sign
        positive_transactions = transactions_forrange.filter(amount__gte=0)
        negative_transactions = transactions_forrange.filter(amount__lte=0)

        # sum them up
        total_made = \
            positive_transactions.aggregate(trans_sum=Sum(F('amount') * F('currency__rate')))[
                'trans_sum'] or 0
        total_spent = \
            negative_transactions.aggregate(trans_sum=Sum(F('amount') * F('currency__rate')))[
                'trans_sum'] or 0

        return total_made, total_spent

    def tag_total_for_daterange(self, user, from_date, to_date):
        """
        Returns a dictionary of grouping by tag and their summed transactions amounts.
        :param user: For specified user
        :param from_date: Start from date
        :param to_date: Ending at date
        :return: dict[Tag] = tag total amount
        """

        tags_withtotal = TaggitTag.objects.filter(transaction__user=user, transaction__date__gte=from_date,
                                                  transaction__date__lte=to_date).annotate(
            tag_total=Sum(F('transaction__amount') * F('transaction__currency__rate')))

        tag_total_dict = {tag_object: tag_object.tag_total for tag_object in tags_withtotal}

        # add special tagg called "untagged" to sum up transactions without tags
        untagged_tag = TaggitTag(id=0, name='Untagged', slug='untagged')
        untagged_user_transactions = Transaction.objects.filter(user=user,
                                                                date__gte=from_date,
                                                                date__lte=to_date,
                                                                tags__isnull=True)

        tag_total_dict[untagged_tag] = untagged_user_transactions.aggregate(
            tag_total=Sum(F('amount') * F('currency__rate')))['tag_total']

        return tag_total_dict


class Transaction(MTModel):
    account = models.ForeignKey(Account,
                                null=True,
                                blank=True,
                                related_name='transactions',
                                on_delete=models.SET_NULL)
    amount = models.FloatField(verbose_name='Amount', default=0.0)
    description = models.CharField(max_length=255, blank=True, verbose_name='Description')
    date = models.DateField()
    recurringparent = models.IntegerField(null=True, blank=True)
    currency = models.ForeignKey(Currency,
                                 null=True,
                                 on_delete=models.SET_NULL)
    signature = models.CharField(verbose_name='Transaction Signature',
                                 max_length=150,
                                 null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True,
                             on_delete=models.SET_NULL)

    tags = TaggableManager(blank=False)
    extra = postgresfields.JSONField(verbose_name='Extra Information',
                                     null=True)
    objects = TransactionManager()

    class Meta:
        ordering = ['-date', '-id']
        db_table = 'walletweb_transaction'

    def __str__(self):
        return 'Transaction for %s' % self.description

    def save(self, *args, **kwargs):
        if self.signature is None:
            self.signature = Transaction.sign_transaction(self)

        super().save(*args, **kwargs)

    @property
    def amountwithuniformcurrency(self):
        if self.currency:
            return self.amount * self.currency.rate

        return self.amount

    @property
    def absoluteamount(self):
        return math.fabs(self.amount)

    @staticmethod
    def sign_transaction(transaction, extra=''):
        # generate transaction signature by hashing (amount, description, date and any extra attributes from caller)
        hasher = hashlib.sha256()
        hasher.update(
            '{0}{1}{2}_{3}'.format(transaction.amount, transaction.description, transaction.date.isoformat(), extra).encode())

        return hasher.hexdigest()


class Tag(MTModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             null=True,
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    words = postgresfields.ArrayField(models.CharField(max_length=100), blank=True, default=list)
    slug = models.SlugField(null=True)

    def __str__(self):
        return 'Tag %s for User %s' % (self.name, self.user)

    class Meta:
        unique_together = ['user', 'slug']
        db_table = 'walletweb_tag'

    @property
    def transactions(self):
        """
        Returns all user transactions associated with this tag.
        :return: QuerySet[Transaction]
        """

walletweb/views/account_views.py
import json

from django.contrib import messages
from django.contrib.auth import mixins
from django.db.models import Max
from django.http import HttpResponse
from django.urls import reverse
from django.views import generic as genericviews

from taggit.models import Tag

from walletweb import models
from walletweb.forms import AccountForm
from walletweb.models import Account


class AccountListView(mixins.LoginRequiredMixin,
                      genericviews.ListView):
    template_name = 'web/account/account_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['display_currency_sign'] = self.request.user.userprofile.display_currency.sign

        return context

    def get_queryset(self):
        user = self.request.user

        return models.Account.objects.filter(user=user).annotate(last_transaction_date=Max('transactions__date'))


class AccountCreateView(mixins.LoginRequiredMixin,
                        genericviews.CreateView):
    form_class = AccountForm
    template_name = 'web/account/account_add.html'

    def form_valid(self, form):
        self.object = form.save()
        user = self.request.user
        self.object.user = user
        afm_resp = super().form_valid(form)

        messages.success(self.request, 'Account created')

        return afm_resp

    def form_invalid(self, form):
        afi_resp = super().form_invalid(form)
        messages.error(self.request, 'Problem in creating account')

        return afi_resp

    def get_success_url(self):
        return reverse('account_list')


class AccountUpdateView(mixins.LoginRequiredMixin,
                        genericviews.UpdateView):
    form_class = AccountForm
    template_name = 'web/account/account_edit.html'

    def get_queryset(self):
        user = self.request.user
        return Account.objects.filter(user=user)

    def get_success_url(self):
        messages.success(self.request, 'Account updated')
        return reverse('account_list')

    def form_invalid(self, form):
        aufi_resp = super().form_invalid(form)
        messages.error(self.request, 'Problem in updating account')

        return aufi_resp


class AccountDeleteView(mixins.LoginRequiredMixin,
                        genericviews.DeleteView):
    model = Account
    template_name = 'web/account/account_confirm_delete.html'

    def get_queryset(self):
        user = self.request.user

        return Account.objects.filter(user=user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['returnurl'] = self.get_success_url()

        return context

    def delete(self, request, *args, **kwargs):
        adel_resp = super().delete(request, *args, **kwargs)
        messages.success(self.request, 'Account deleted')

        return adel_resp

    def get_success_url(self):
        return reverse('account_list')


class AccountTagsView(mixins.LoginRequiredMixin,
                      genericviews.View):
    def get(self, request, *args, **kwargs):
        user = request.user
        tags = list(Tag.objects.filter(transaction__user=user).distinct().values_list("name", flat=True))
        return HttpResponse(json.dumps(tags))

templates/web/account/account_add.html
{% extends 'web/base.html' %}

{% block title %}
Add Account
{% endblock %}

{% block content %}
<div class="columns">
  <div class="column is-6">
    <form method='post' class="">
      {% csrf_token %}

      {% include "generic_snippets/form_snippet.html" with form=form %}

      <div class="form-actions">
        <input class="button is-primary" type='submit' value='Add'/>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/web/account/account_confirm_delete.html
{% extends 'web/base.html' %}

{% block title %}
Delete Account
{% endblock %}

{% block content %}
<div class="columns is-vcentered">
  <div class="column is-narrow"><span>Are you sure you want to delete this account?</span></div>
  <div class="column has-text-left">
    <form method="post" class="is-inline-block">
      {% csrf_token %}
      <input class="button is-danger" type="submit" value="Yes">
    </form>
    <a href="{{ returnurl }}" class="button is-light">No</a>
  </div>
</div>
{% endblock content %}
`

templates/web/account/account_edit.html
{% extends 'web/base.html' %}

{% block title %}
Edit Account
{% endblock %}

{% block content %}
<div class="columns">
  <div class="column is-6">
    <form method='post'>
      {% csrf_token %}

      {% include "generic_snippets/form_snippet.html" with form=form %}

      <div>
        <input class="button is-primary" type='submit' value='Update'/>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/web/account/account_list.html
{% extends 'web/base.html' %}
{% load utiltags %}

{% block title %}
  Account Listing
{% endblock %}

{% block content %}
  {% show_account_list %}
{% endblock content %}

templates/web/account/account_list_partial.html
{% load utiltags %}
{% load static %}

<div class="content-box-content">
    <table class="table is-striped is-fullwidth">
        <thead>
        <tr>
            <th>
                Account
            </th>
            <th>
                Balance
            </th>
            <th>Last Transaction</th>
            <th>
                <div class="is-pulled-right">
                    <a href="{% url 'account_add' %}"><span class="fas fa-plus-square"></span></a>
                </div>
            </th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="6">
              {% show_pager %}
            </td>
        </tr>
        </tfoot>
        <tbody>
        {% for acct in page_obj.object_list %}
            <tr>
                <td>
                    <a href='{% url 'transaction_list' acct.id %}'>{{ acct.name }}</a>
                </td>
                <td>
                  {{ acct.balance|colorize_amount:display_currency_sign }}
                </td>
                <td>
                  {{ acct.last_transaction_date|default_if_none:"" }}
                </td>
                <td class="has-text-right">

                    <a href='{% url 'account_delete' acct.id %}'>
                        <span class="icon"><i class="fas fa-trash"></i></span>
                    </a>
                    <a href='{% url 'account_edit' acct.id %}'>
                        <span class="icon"><i class="fas fa-edit"></i></span>
                    </a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td>
                    No accounts defined yet. Care to <a href='{% url 'account_add' %}'>add</a> one?
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>