api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from api import views

app_name = 'api'

router = routers.SimpleRouter()
router.register(r'transaction', views.TransactionViewSet)

urlpatterns = [
    url(r'^', include(router.urls)),
    # url(r'transaction/chart/monthly$',
    #     views.TransactionChartMonthlyDataView.as_view(),
    #     name='api-transaction-chart-data-monthly'
    #     ),
    url(r'account/$',
        views.AccountListView.as_view(),
        name='api-account-list'
        ),

    url(r'currency/$',
        views.CurrencyListView.as_view(),
        name='api-currency-list'
        ),

    url(r'tag/$',
        views.TagListView.as_view(),
        name='api-tag-list')
]

walletweb/models.py
import hashlib

import math
from collections import defaultdict
from decimal import Decimal

from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser, BaseUserManager
from django.contrib.postgres import fields as postgresfields
from django.core import mail
from django.db import models
from django.db.models import F
from django.db.models import Sum
from django.conf import settings
from django.utils.text import slugify

from taggit.managers import TaggableManager
from taggit.models import Tag as TaggitTag


class MTUserManager(BaseUserManager):
    def create_user(self, email, password=None, first_name='', last_name=''):
        user = self.model()

        if not email:
            raise ValueError('An email address must be specified')

        user.email = email

        if password:
            user.set_password(password)
        else:
            user.set_unusable_password()

        user.first_name = first_name or 'MT User'
        user.last_name = last_name or ''

        user.save()

        return user

    def create_superuser(self, email, password, first_name, last_name):
        user = self.create_user(email, password, first_name, last_name)
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True

        user.save()

        return user


class WalletyUser(AbstractBaseUser,
                  PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=50,
                                  blank=True)
    last_name = models.CharField(max_length=50,
                                 blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']
    objects = MTUserManager()

    def get_short_name(self):
        return self.email

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        mail.send_mail(subject, message, from_email, [self.email], **kwargs)

    class Meta:
        db_table = 'walletweb_walletyuser'

    def __str__(self):
        return self.email


class MTModel(models.Model):
    created_at = models.DateTimeField(verbose_name='Created at',
                                      auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Updated at',
                                      auto_now=True)

    class Meta:
        abstract = True


class UserProfile(MTModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    display_currency = models.ForeignKey('Currency', on_delete=models.CASCADE)

    class Meta:
        db_table = 'walletweb_userprofile'

    def __str__(self):
        return 'Profile for {0}'.format(self.user)


class Currency(MTModel):
    sign = models.CharField(verbose_name='Currency Sign',
                            max_length=5)
    name = models.CharField(verbose_name='Currency Name',
                            max_length=100)
    rate = models.FloatField(verbose_name='Rate to USD',
                             default=1.0)

    class Meta:
        db_table = 'walletweb_currency'

    def __str__(self):
        return self.name


class Account(MTModel):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True,
                             on_delete=models.SET_NULL)
    currency = models.ForeignKey(Currency,
                                 verbose_name='Default Account Currency',
                                 null=True,
                                 on_delete=models.SET_NULL)

    @property
    def balance(self):
        # fetch display currency set by user
        display_currency = self.user.userprofile.display_currency

        account_transactions = Transaction.objects.filter(account=self.id)
        # calculate account balance using the display currency rate
        trans_sum = account_transactions.aggregate(trans_sum=Sum(F('amount') * display_currency.rate))[
                        'trans_sum'] or 0

        return trans_sum

    def __str__(self):
        return 'Account %s' % self.name

    class Meta:
        unique_together = ('name', 'user')
        db_table = 'walletweb_account'


class TransactionManager(models.Manager):
    def made_spent_breakdown_for_daterange(self, user, from_date, to_date):
        """
        Returns the total made and total spent for specified user and date range.
        :param user: For specified user
        :param from_date: Start from date
        :param to_date: Ending at date
        :return: tuple (made, spent)
        """
        # for transactions during a certain date range
        transactions_forrange = Transaction.objects.filter(user=user,
                                                            date__gte=from_date,
                                                            date__lte=to_date)

        # breakdown transactions for date range by sign
        positive_transactions = transactions_forrange.filter(amount__gte=0)
        negative_transactions = transactions_forrange.filter(amount__lte=0)

        # sum them up
        total_made = \
            positive_transactions.aggregate(trans_sum=Sum(F('amount') * F('currency__rate')))[
                'trans_sum'] or 0
        total_spent = \
            negative_transactions.aggregate(trans_sum=Sum(F('amount') * F('currency__rate')))[
                'trans_sum'] or 0

        return total_made, total_spent

    def tag_total_for_daterange(self, user, from_date, to_date):
        """
        Returns a dictionary of grouping by tag and their summed transactions amounts.
        :param user: For specified user
        :param from_date: Start from date
        :param to_date: Ending at date
        :return: dict[Tag] = tag total amount
        """

        tags_withtotal = TaggitTag.objects.filter(transaction__user=user, transaction__date__gte=from_date,
                                                  transaction__date__lte=to_date).annotate(
            tag_total=Sum(F('transaction__amount') * F('transaction__currency__rate')))

        tag_total_dict = {tag_object: tag_object.tag_total for tag_object in tags_withtotal}

        # add special tagg called "untagged" to sum up transactions without tags
        untagged_tag = TaggitTag(id=0, name='Untagged', slug='untagged')
        untagged_user_transactions = Transaction.objects.filter(user=user,
                                                                date__gte=from_date,
                                                                date__lte=to_date,
                                                                tags__isnull=True)

        tag_total_dict[untagged_tag] = untagged_user_transactions.aggregate(
            tag_total=Sum(F('amount') * F('currency__rate')))['tag_total']

        return tag_total_dict


class Transaction(MTModel):
    account = models.ForeignKey(Account,
                                null=True,
                                blank=True,
                                related_name='transactions',
                                on_delete=models.SET_NULL)
    amount = models.FloatField(verbose_name='Amount', default=0.0)
    description = models.CharField(max_length=255, blank=True, verbose_name='Description')
    date = models.DateField()
    recurringparent = models.IntegerField(null=True, blank=True)
    currency = models.ForeignKey(Currency,
                                 null=True,
                                 on_delete=models.SET_NULL)
    signature = models.CharField(verbose_name='Transaction Signature',
                                 max_length=150,
                                 null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True,
                             on_delete=models.SET_NULL)

    tags = TaggableManager(blank=False)
    extra = postgresfields.JSONField(verbose_name='Extra Information',
                                     null=True)
    objects = TransactionManager()

    class Meta:
        ordering = ['-date', '-id']
        db_table = 'walletweb_transaction'

    def __str__(self):
        return 'Transaction for %s' % self.description

    def save(self, *args, **kwargs):
        if self.signature is None:
            self.signature = Transaction.sign_transaction(self)

        super().save(*args, **kwargs)

    @property
    def amountwithuniformcurrency(self):
        if self.currency:
            return self.amount * self.currency.rate

        return self.amount

    @property
    def absoluteamount(self):
        return math.fabs(self.amount)

    @staticmethod
    def sign_transaction(transaction, extra=''):
        # generate transaction signature by hashing (amount, description, date and any extra attributes from caller)
        hasher = hashlib.sha256()
        hasher.update(
            '{0}{1}{2}_{3}'.format(transaction.amount, transaction.description, transaction.date.isoformat(), extra).encode())

        return hasher.hexdigest()


class Tag(MTModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             null=True,
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    words = postgresfields.ArrayField(models.CharField(max_length=100), blank=True, default=list)
    slug = models.SlugField(null=True)

    def __str__(self):
        return 'Tag %s for User %s' % (self.name, self.user)

    class Meta:
        unique_together = ['user', 'slug']
        db_table = 'walletweb_tag'

    @property
    def transactions(self):
        """
        Returns all user transactions associated with this tag.
        :return: QuerySet[Transaction]
        """

templates/web/base.html
{% load utiltags %}
{% load static %}
{% load render_bundle from webpack_loader %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  {% render_bundle 'main' %}

    <title>{% block title %}{% endblock title %} :: MoneyTracker</title>

    <link rel="stylesheet" href="{% static  'css/bulmaswatch.min.css' %}">
    <link rel="stylesheet" href="{% static  'css/mt_overrides.css' %}">
  {% block extracss %}{% endblock extracss %}
</head>
<body>
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'home' %}">
            MoneyTracker
          {#            <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox"#}
          {#                 width="112" height="28">#}
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>
    <div class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item {% highlight_if_active 'dashboard' %}" href="{% url 'dashboard' %}">
                <span class="icon"><i class="fas fa-home"></i></span>
                <span>Home</span>
            </a>

            <a class="navbar-item {% highlight_if_active 'account_list' %}" href="{% url 'account_list' %}">
                <span class="icon"><i class="fas fa-book"></i></span>
                <span>Accounts</span>
            </a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    <span class="icon"><i class="fas fa-money-bill-alt"></i></span>
                    <span>Transactions</span>
                </a>

                <div class="navbar-dropdown is-boxed">
                    <a class="navbar-item {% highlight_if_active 'transaction_list_all' %}"
                       href="{% url 'transaction_list_all' %}">
                        <span class="icon"><i class="fa fa-list"></i></span>
                        <span>Transaction List</span>
                    </a>
                    <a class="navbar-item {% highlight_if_active 'transaction_upload' %}"
                       href="{% url 'transaction_upload' %}">
                        <span class="icon"><i class="fa fa-upload"></i></span>
                        <span>Transaction Upload</span>
                    </a>
                </div>
            </div>

            <a class="navbar-item {% highlight_if_active 'transaction_chart' %}" href="{% url 'transaction_chart' %}">
                <span class="icon"><i class="fa fa-chart-area"></i></span>
                <span>Charts</span>
            </a>
            <a class="navbar-item {% highlight_if_active 'rtransaction_list' %}" href="{% url 'rtransaction_list' %}">
                <span class="icon"><i class="fa fa-redo"></i></span>
                <span>Recurring Transactions</span>
            </a>
            <a class="navbar-item {% highlight_if_active 'tag_list' %}" href="{% url 'tag_list' %}">
                <span class="icon"><i class="fa fa-tags"></i></span>
                <span>Tags</span>
            </a>
        </div>

        <div class="navbar-end">
            <a class="navbar-item" href="{% url 'contactme' %}">Contact</a>
          {% if user.is_authenticated %}
              <div class="navbar-item has-dropdown is-hoverable">
                  <a class="navbar-link">
                      <i class="icon-user"></i>{{ user.first_name }} <span
                          class="caret"></span>
                  </a>
                  <div class="navbar-dropdown is-boxed">
                      <a class="navbar-item" href="{% url 'logout' %}">Sign Out</a>
                  </div>
              </div>
          {% endif %}
        </div>
    </div>
</nav>

<section class="section">
    <div class="container">
      {% if messages %}
        {% for message in messages %}
            <div class="notification is-{{ message.tags }}">
                <button class="delete"></button>
              {{ message }}
            </div>
        {% endfor %}
      {% endif %}
      {% block content %}
      {% endblock content %}
    </div>
</section>

<footer class="footer">
    <div class="container">
        <div class="content has-text-centered">
            <p>
                <small>
                    &#169; Copyright 2018 | Powered by the giant brain of <a href="http://codedemigod.com">Alaa
                                                                                                           Salman</a>.
                    The website content
                    is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>..
                </small>
            </p>
        </div>
    </div>
</footer>
{% block extrajs %}{% endblock extrajs %}
{% if USE_GOOGLE_ANALYTICS %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-37953963-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag () {dataLayer.push(arguments);}

        gtag('js', new Date());

        gtag('config', 'UA-37953963-1');
    </script>
{% endif %}
</body>
</html>

templates/web/contactme.html
{% extends 'web/base.html' %}

{% block title %}
  About Page
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <form method='post' class="form-horizontal">
              {% csrf_token %}

              {% include "generic_snippets/form_snippet.html" with form=form %}

                <div class="form-actions">
                    <input class="button" type='submit' value='Send'/>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

templates/web/contactme_submitted.html
{% extends 'web/base.html' %}

{% block title %}
  About Page
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <p>Submitted via email.
        </div>
    </div>
{% endblock content %}

templates/web/index.html
{% extends 'web/base.html' %}
{% load utiltags %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
<h1 class="title">Welcome {{ user.first_name|default:"Money Tracker" }}</h1>

<div class="columns">
  <div class="column">
    <h4>For the month of {{ this_month }} you've:</h4>
    <table class="table is-fullwidth">
      <tr>
        <td>Spent:</td>
        <td>{{ total_spent_thismonth|colorize_amount:display_currency_sign }}</td>
      </tr>
      <tr>
        <td>Made:</td>
        <td>{{ total_made_thismonth|colorize_amount:display_currency_sign }}</td>
      </tr>
    </table>
    {% if tag_total_dict_thismonth %}
    <h4>Here's the breakdown:</h4>
    <table class="table">
      {% for tag, tag_total in tag_total_dict_thismonth.items %}
      <tr>
        <td>{{ tag.name }}</td>
        <td>{{ tag_total|colorize_amount:display_currency_sign }}</td>
      </tr>
      {% endfor %}
    </table>
    {% endif %}
  </div>
  <div class="column">
    <h4>Compared to last month {{ last_month }} where you've:</h4>
    <table class="table is-fullwidth">
      <tr>
        <td>Spent:</td>
        <td>{{ total_spent_lastmonth|colorize_amount:display_currency_sign }}</td>
      </tr>
      <tr>
        <td>Made:</td>
        <td>{{ total_made_lastmonth|colorize_amount:display_currency_sign }}</td>
      </tr>
    </table>
    {% if tag_total_dict_lastmonth %}
    <h4>Here's the breakdown:</h4>
    <table class="table">
      {% for tag, tag_total in tag_total_dict_lastmonth.items %}
      <tr>
        <td>{{ tag.name }}</td>
        <td>{{ tag_total|colorize_amount:display_currency_sign }}</td>
      </tr>
      {% endfor %}
    </table>
    {% endif %}
  </div>
</div>

{% endblock content %}

templates/web/pager.html
<nav class="pagination is-right" role="navigation" aria-label="pagination">
    <ul class="pagination-list">
      {% if firstlink %}
          <li><a href="?{{ firstlink }}" title="First Page" class="pagination-previous">&laquo; First</a></li>
      {% endif %}

      {% if page_obj.has_previous %}
          <li><a href="?{{ prevlink }}" title="Previous Page" class="pagination-previous">&lt; Previous</a></li>
      {% endif %}

      {% for link in pagelinks %}
          <li><a href="?{{ link.href }}" title="{{ link.title }}" class="{{ link.class }}">{{ link.value }}</a></li>
      {% endfor %}

      {% if page_obj.has_next %}
          <li><a href="?{{ nextlink }}" title="Next Page" class="pagination-next">Next &gt;</a></li>
      {% endif %}

      {% if lastlink %}
          <li><a href="?{{ lastlink }}" title="Last Page" class="pagination-next">Last &raquo;</a></li>
      {% endif %}
    </ul>
</nav>

templates/web/transaction_chart.html
{% extends 'web/base.html' %}
{% load utiltags %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block title %}
  Expenses Chart
{% endblock %}

{% block extracss %}
{% endblock extracss %}

{% block extrajs %}
  {% render_bundle 'filter' %}
  {% render_bundle 'vcharts' %}

    <script type="text/javascript" src="{% static "scripts/mt.js" %}"></script>
{% endblock %}

{% block content %}
    <div id="transfilter">
        <transaction-filter
                from-date="{{ from_date }}"
                to-date="{{ to_date }}"
                account-tags-url="{% url 'api:api-tag-list' %}"
                :tags-value="{{ tags__have }}">
        </transaction-filter>
    </div>
    <div id="vue-chart-container">
        <transaction-chart
                monthly-url="{% url 'api:transaction-chart-data-monthly' %}"
                yearly-url="{% url 'api:transaction-chart-data-yearly' %}"
                pie-url="{% url 'api:transaction-chart-data-pie' %}"
                from-date="{{ from_date }}"
                to-date="{{ to_date }}">
        </transaction-chart>
    </div>
{% endblock content %}